import Image from "next/image";
import Link from "next/link";

function Mark() { return <span className="mark" aria-hidden="true"><i /><i /><i /><i /></span>; }

export default function LandingPage() {
  return <main className="landing">
    <nav className="landing-nav"><Link href="/" className="brand"><Mark /> <span>Ops Ninja</span></Link><div className="nav-links"><a href="#how-it-works">How it works</a><a href="#approval">Approval gate</a></div><Link className="button button-quiet" href="/home">Open workspace</Link></nav>
    <section className="hero"><div className="hero-copy"><p className="eyebrow"><span className="signal" /> Meeting intelligence, under your control</p><h1>Turn the meeting into <em>the next move.</em></h1><p className="hero-lede">Ops Ninja extracts the signal from every conversation, connects it to your operational memory, and puts every real-world action behind a deliberate human decision.</p><div className="hero-actions"><Link className="button button-primary" href="/home">Enter command center</Link><a className="text-link" href="#how-it-works">See the flow <span>↓</span></a></div><div className="integration-line"><span>Meeting intelligence for</span><b>Obsidian</b><i /> <b>Jira</b><i /> <b>Slack</b></div></div>
      <div className="hero-system" aria-label="Ops Ninja meeting workflow"><div className="system-topline"><span><i className="live-dot" /> Live processing</span><span>12:08:42</span></div><div className="system-flow"><div className="flow-card transcript-card"><span className="card-kicker">Input</span><strong>Product sync transcript</strong><p>“Let&apos;s keep the Oct 18 release...”</p><small>46 minutes · 4 speakers</small></div><span className="flow-rail" /><div className="flow-card extraction-card"><span className="ai-label">AI extraction</span><div className="scan-lines"><i /><i /><i /></div><p>3 decisions found</p><p>3 action items found</p></div><span className="flow-rail" /><div className="flow-card mom-card"><span className="card-kicker">Structured MOM</span><strong>Project Orca</strong><div className="mom-row"><i /> October 18 release</div><div className="mom-row"><i /> API access is blocked</div></div></div><div className="approval-preview"><div className="approval-icon">!</div><div><span>Approval required</span><strong>Create Jira issue in ORCA</strong></div><button type="button">Review action</button></div><div className="network-thread thread-a" /><div className="network-thread thread-b" /><span className="system-node node-one" /><span className="system-node node-two" /><span className="system-node node-three" /></div></section>
    <section id="how-it-works" className="proof-band"><p className="eyebrow">A closed operational loop</p><div className="proof-grid"><div><span>01</span><h2>Capture the record</h2><p>Transcript becomes a structured, editable MOM with decisions, risks, owners, and deadlines.</p></div><div><span>02</span><h2>Connect the context</h2><p>Meeting notes become linked Obsidian records, ready for questions across people, projects, and actions.</p></div><div><span>03</span><h2>Act with intent</h2><p>The orchestrator proposes the smallest useful Jira or Slack action. You decide if it leaves the vault.</p></div></div></section>
    <section id="approval" className="approval-statement"><div><p className="eyebrow orange-eyebrow">The approval gate</p><h2>AI can prepare the work.<br />Only you can release it.</h2></div><p>Every external write carries its source, destination, and consequence forward. There are no invisible automations, only clear proposals and accountable outcomes.</p></section>
    <footer><span className="brand"><Mark /> Ops Ninja</span><span>Operational clarity, one approved action at a time.</span><Image src="/logo.png" alt="" width={100} height={54} /></footer>
  </main>;
}
